version: '3'

services:
  server:
    container_name: rate_limiter_server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./.env:/.env
    env_file:
      - ./.env

  redis:
    container_name: rate_limiter_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local